### ISSUE TITLE
Těm tlačítkům stačí málo k dokonalosti

### ISSUE THREAD

**Issue by mohlerit** [Adwir/PROJEKT-Vizitka#1]
Ahoj, koukal jsem na to a fotku Elišky máš z  něakého důvodu posutunutou jen o 50px. Velikost je 150x150px takže by posutnutí mělo být o 75px. To by mi tolik nevadilo, ale tlačítka by to chtělo doladit. Chybí ti u nich padding: 5px;

Zarovnání celé vizitky `left: 30%;` taky není dobře. Použil bych `margin-left:auto; margin-right:auto;` Tím pádem to bude uprostřed.

**Comment by Adwir** [comment]
Nevsimla jsem si, ze mam ukol stale oznaceny za neodevzdany. Tady je doplneni.
